FROM --platform=linux/amd64 continuumio/miniconda:latest

RUN conda create -n scipy24 numba/label/dev::numba=0.61.0dev0 numba/label/dev::llvmlite=0.44.0dev0 setuptools clang=14 python=3.11 gcc_linux-64 gxx_linux-64 cython


